### ISSUE TITLE
How much work is there to release a stable version?

### ISSUE THREAD

**Issue by Taitava** [madmatt/silverstripe-encrypt-at-rest#7]
Hi,

I'm new to this module and actually haven't even tested it yet. As I haven't found any other encrypting module for SilverStripe, I'm keen to know how far away is this from being production safe (= stable)? If you need help, I can fork it and make some pull requests. I'm not an expert in encryption/security, but I know SilverStripe quite well. Thanks!

**Comment by Firesphere** [comment]
Hi @Taitava,

There's quite some work that still needs to be done on this before we can call it a stable release. Most important is checking for the heading-key to be set, and the get/set methods to return casted values instead of just strings.

We haven't had time to completely make a finished product yet, but this is already being used in websites to encrypt and decrypt the data in the database.

Considering the usage, as described in the readme, is incomplete.
For each dataobject that uses encrypted values (EncryptedVarchar, EncryptedEnum etc.), the dataobject needs to get the EncryptDataObjectFields like in the _config.yml

**Comment by madmatt** [comment]
7 years later, but version 1.0.0 is now released, targeting Silverstripe CMS 4... only the last stable version of Silverstripe CMS 😅

**Comment by Taitava** [comment]
😎 Congratulations for the stable release! 🎉
